[package]
name = "roxy-dbc"
version = "0.7.0"
edition = "2024"

[dependencies]
can-dbc = "10.0"
bytemuck = "1"
log = "0.4"
wgpu = "28"
winit = "0.30"
pollster = "1.0"
env_logger = "0.11"
rfd = "0.17"
roxmltree = "0.21"
encoding_rs = "0.8"
dear-imgui-rs = "0.18"
dear-imgui-winit = "0.18"
dear-imgui-wgpu = { version = "0.18", default-features = false, features = ["wgpu-28"] }
