//! 将 EditableFibex 序列化为 ASAM FIBEX 3.1.1 XML

use crate::fibex::editable_fibex::*;
use crate::fibex::export::escape_xml;

pub fn export_fibex(fibex: &EditableFibex) -> String {
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<fx:FIBEX VERSION=\"3.1.1\" ");
    out.push_str("xmlns:fx=\"http://www.asam.net/xml/fbx\" ");
    out.push_str("xmlns:ho=\"http://www.asam.net/xml\" ");
    out.push_str("xmlns:fr=\"http://www.asam.net/xml/fbx/flexray\" ");
    out.push_str("xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" ");
    out.push_str("xsi:schemaLocation=\"http://www.asam.net/xml/fbx fibex.xsd\">\n");

    let cluster = fibex.cluster();
    let cluster_id = id_of("Cluster", &cluster.name);
    let channel_a_id = id_of(&cluster_id, "ChannelA");
    let channel_b_id = id_of(&cluster_id, "ChannelB");

    // ------------------------------------------------------------------
    // PROJECT（含 CONTROLLERS / ECU）
    // ------------------------------------------------------------------
    out.push_str("  <fx:PROJECT ID=\"PROJ_roxy\">\n");
    out.push_str("    <ho:SHORT-NAME>RoxyFibexProject</ho:SHORT-NAME>\n");
    out.push_str("    <fx:DESC>Generated by roxy-fibex</fx:DESC>\n");
    out.push_str("    <fx:CONTROLLERS>\n");
    for ecu in fibex.ecus() {
        out.push_str(&format!(
            "      <ho:CONTROLLER ID=\"{}\">\n",
            escape_xml(&id_of("ECU", ecu))
        ));
        out.push_str(&format!(
            "        <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
            escape_xml(ecu)
        ));
        out.push_str("      </ho:CONTROLLER>\n");
    }
    out.push_str("    </fx:CONTROLLERS>\n");
    out.push_str("    <fx:FEATURES>\n");
    out.push_str("      <fx:PROTOCOLS>\n");
    out.push_str("        <fx:PROTOCOL>FRING</fx:PROTOCOL>\n");
    out.push_str("      </fx:PROTOCOLS>\n");
    out.push_str("    </fx:FEATURES>\n");
    out.push_str("  </fx:PROJECT>\n");

    // ------------------------------------------------------------------
    // ELEMENTS
    // ------------------------------------------------------------------
    out.push_str("  <fx:ELEMENTS>\n");

    // CLUSTER
    let p = &cluster.params;
    out.push_str(&format!(
        "    <fx:CLUSTER ID=\"{}\">\n",
        escape_xml(&cluster_id)
    ));
    out.push_str(&format!(
        "      <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
        escape_xml(&cluster.name)
    ));
    out.push_str("      <fx:PROTOCOL VERSION=\"2005\">FRING</fx:PROTOCOL>\n");
    out.push_str(&format!("      <fx:SPEED>{}</fx:SPEED>\n", p.speed_kbps));
    out.push_str(&format!(
        "      <fx:COMMUNICATION-PATTERN>\n        <fx:CYCLE>MULTIPLIED</fx:CYCLE>\n        <fx:CYCLE-TIME-ms>{}</fx:CYCLE-TIME-ms>\n      </fx:COMMUNICATION-PATTERN>\n",
        fmt_f64(p.cycle_time_ms)
    ));
    out.push_str(&format!(
        "      <fx:COLDSTART-ATTEMPTS>{}</fx:COLDSTART-ATTEMPTS>\n",
        p.coldstart_attempts
    ));
    out.push_str(&format!(
        "      <fx:ACTION-POINT-OFFSET>{}</fx:ACTION-POINT-OFFSET>\n",
        p.action_point_offset
    ));
    out.push_str(&format!(
        "      <fx:MINISLOT-ACTION-POINT-OFFSET>{}</fx:MINISLOT-ACTION-POINT-OFFSET>\n",
        p.minislot_action_point_offset
    ));
    out.push_str(&format!(
        "      <fx:DYNAMIC-SLOT-IDLE-PHASE>{}</fx:DYNAMIC-SLOT-IDLE-PHASE>\n",
        p.dynamic_slot_idle_phase
    ));
    out.push_str(&format!(
        "      <fx:MACROTICK-DURATION>{}</fx:MACROTICK-DURATION>\n",
        fmt_f64(p.macrotick_duration_us / 1000.0)
    ));
    out.push_str(&format!(
        "      <fx:MINOR-VERSION>{}</fx:MINOR-VERSION>\n",
        p.minor_version
    ));
    out.push_str(&format!(
        "      <fx:NETWORK-IDLE-TIME>{}</fx:NETWORK-IDLE-TIME>\n",
        p.network_idle_time
    ));
    out.push_str(&format!(
        "      <fx:NUMBER-OF-MINISLOTS>{}</fx:NUMBER-OF-MINISLOTS>\n",
        p.number_of_minislots
    ));
    out.push_str(&format!(
        "      <fx:NUMBER-OF-STATIC-SLOTS>{}</fx:NUMBER-OF-STATIC-SLOTS>\n",
        p.number_of_static_slots
    ));
    out.push_str(&format!(
        "      <fx:MINISLOT-DURATION>{}</fx:MINISLOT-DURATION>\n",
        p.minislot_duration
    ));
    out.push_str(&format!(
        "      <fx:STATIC-SLOT-DURATION>{}</fx:STATIC-SLOT-DURATION>\n",
        p.static_slot_duration
    ));
    out.push_str(&format!(
        "      <fx:SYMBOL-WINDOW>{}</fx:SYMBOL-WINDOW>\n",
        p.symbol_window
    ));
    out.push_str(&format!(
        "      <fx:SYMBOL-WINDOW-IDLE-PHASE>{}</fx:SYMBOL-WINDOW-IDLE-PHASE>\n",
        p.symbol_window_idle_phase
    ));
    out.push_str(&format!(
        "      <fx:OFFSET-CORRECTION-START>{}</fx:OFFSET-CORRECTION-START>\n",
        p.offset_correction_start
    ));

    // CHANNELS（Static Segment SLOTS + FRAME-TRIGGERINGS）
    out.push_str("      <fx:CHANNELS>\n");
    for (channel_id, channel_name, ch) in [
        (&channel_a_id, "ChannelA", FrChannel::A),
        (&channel_b_id, "ChannelB", FrChannel::B),
    ] {
        out.push_str(&format!(
            "        <fx:CHANNEL ID=\"{}\">\n",
            escape_xml(channel_id)
        ));
        out.push_str(&format!(
            "          <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
            channel_name
        ));
        out.push_str("          <fx:STATIC-PART>\n");
        out.push_str("            <fx:SLOTS>\n");

        // 按 slot 分组该通道上的帧触发
        let mut slots: Vec<(u32, Vec<&EditableFrame>)> = Vec::new();
        for frame in fibex.frames() {
            if !frame.triggering().channel.covers(ch) {
                continue;
            }
            let slot_id = frame.triggering().slot_id;
            if let Some(entry) = slots.iter_mut().find(|(id, _)| *id == slot_id) {
                entry.1.push(frame);
            } else {
                slots.push((slot_id, vec![frame]));
            }
        }
        slots.sort_by_key(|(id, _)| *id);

        for (slot_id, frames) in &slots {
            out.push_str(&format!(
                "              <fx:SLOT ID=\"{}\">\n",
                escape_xml(&id_of(channel_id, &format!("StaticSlot{}", slot_id)))
            ));
            out.push_str(&format!(
                "                <ho:SHORT-NAME>StaticSlot{}</ho:SHORT-NAME>\n",
                slot_id
            ));
            out.push_str(&format!(
                "                <fx:SLOT-ID>{}</fx:SLOT-ID>\n",
                slot_id
            ));
            out.push_str("                <fx:FRAME-TRIGGERINGS>\n");
            for frame in frames {
                let t = frame.triggering();
                out.push_str(&format!(
                    "                  <fx:FRAME-TRIGGERING ID=\"{}\">\n",
                    escape_xml(&id_of(channel_id, &format!("{}_Trigger", frame.name())))
                ));
                out.push_str("                    <fx:TIMINGS>\n");
                out.push_str(&format!(
                    "                      <fx:CYCLE-REPETITION>{}</fx:CYCLE-REPETITION>\n",
                    t.cycle_repetition
                ));
                out.push_str(&format!(
                    "                      <fx:BASE-CYCLE>{}</fx:BASE-CYCLE>\n",
                    t.base_cycle
                ));
                out.push_str("                    </fx:TIMINGS>\n");
                out.push_str(&format!(
                    "                    <fx:FRAME-REF REF-TYPE=\"fx:FRAME-TYPE\" ID-REF=\"{}\"/>\n",
                    escape_xml(&id_of("FRAME", frame.name()))
                ));
                out.push_str("                  </fx:FRAME-TRIGGERING>\n");
            }
            out.push_str("                </fx:FRAME-TRIGGERINGS>\n");
            out.push_str("              </fx:SLOT>\n");
        }

        out.push_str("            </fx:SLOTS>\n");
        out.push_str("          </fx:STATIC-PART>\n");
        out.push_str("        </fx:CHANNEL>\n");
    }
    out.push_str("      </fx:CHANNELS>\n");
    out.push_str("    </fx:CLUSTER>\n");

    // CODING（每个信号一段，按名称生成 ID）
    let mut used_codings: std::collections::HashSet<String> = std::collections::HashSet::new();
    for pdu in fibex.pdus() {
        for sig in pdu.signals() {
            let coding_id = coding_id_of(pdu.name(), sig.name());
            if !used_codings.insert(coding_id.clone()) {
                continue;
            }
            out.push_str(&format!(
                "    <ho:CODING ID=\"{}\">\n",
                escape_xml(&coding_id)
            ));
            out.push_str(&format!(
                "      <ho:SHORT-NAME>{}_Coding</ho:SHORT-NAME>\n",
                escape_xml(sig.name())
            ));
            out.push_str("      <ho:CODED-TYPE>\n");
            out.push_str(&format!(
                "        <ho:BIT-LENGTH>{}</ho:BIT-LENGTH>\n",
                sig.length_bits()
            ));
            out.push_str(&format!(
                "        <ho:SIGN-CONVENTION>{}</ho:SIGN-CONVENTION>\n",
                match sig.value_type() {
                    ValueType::Signed => "TWOS-COMPLEMENT",
                    ValueType::Unsigned => "UNSIGNED",
                }
            ));
            out.push_str("      </ho:CODED-TYPE>\n");
            out.push_str("      <ho:COMPU-METHOD>\n");
            out.push_str("        <ho:SCALES>\n");
            // 物理量程 + 线性换算系数
            out.push_str("          <ho:SCALE>\n");
            out.push_str(&format!(
                "            <ho:LOWER-LIMIT>{}</ho:LOWER-LIMIT>\n",
                fmt_f64(sig.min())
            ));
            out.push_str(&format!(
                "            <ho:UPPER-LIMIT>{}</ho:UPPER-LIMIT>\n",
                fmt_f64(sig.max())
            ));
            out.push_str("            <ho:COMPU>\n");
            out.push_str("              <ho:COMPU-RATIONAL-COEFFS>\n");
            out.push_str("                <ho:COMPU-NUMERATOR>\n");
            out.push_str(&format!(
                "                  <ho:V>{}</ho:V>\n",
                fmt_f64(sig.offset())
            ));
            out.push_str(&format!(
                "                  <ho:V>{}</ho:V>\n",
                fmt_f64(sig.factor())
            ));
            out.push_str("                </ho:COMPU-NUMERATOR>\n");
            out.push_str("                <ho:COMPU-DENOMINATOR>\n");
            out.push_str("                  <ho:V>1</ho:V>\n");
            out.push_str("                </ho:COMPU-DENOMINATOR>\n");
            out.push_str("              </ho:COMPU-RATIONAL-COEFFS>\n");
            out.push_str("            </ho:COMPU>\n");
            out.push_str("            <ho:FUNCTION-CHANNEL>\n");
            out.push_str("              <ho:UNIT>\n");
            out.push_str(&format!(
                "                <ho:DISPLAY-NAME>{}</ho:DISPLAY-NAME>\n",
                escape_xml(sig.unit())
            ));
            out.push_str("              </ho:UNIT>\n");
            out.push_str("            </ho:FUNCTION-CHANNEL>\n");
            out.push_str("          </ho:SCALE>\n");
            // 值描述
            for (value, desc) in sig.value_descriptions() {
                out.push_str("          <ho:SCALE>\n");
                out.push_str(&format!(
                    "            <ho:LOWER-LIMIT>{}</ho:LOWER-LIMIT>\n",
                    value
                ));
                out.push_str(&format!(
                    "            <ho:UPPER-LIMIT>{}</ho:UPPER-LIMIT>\n",
                    value
                ));
                out.push_str("            <ho:COMPU>\n");
                out.push_str("              <ho:COMPU-CONST>\n");
                out.push_str(&format!(
                    "                <ho:VT>{}</ho:VT>\n",
                    escape_xml(desc)
                ));
                out.push_str("              </ho:COMPU-CONST>\n");
                out.push_str("            </ho:COMPU>\n");
                out.push_str("          </ho:SCALE>\n");
            }
            out.push_str("        </ho:SCALES>\n");
            out.push_str("        <ho:COMPU-DEFAULT-VALUE>0</ho:COMPU-DEFAULT-VALUE>\n");
            out.push_str("      </ho:COMPU-METHOD>\n");
            out.push_str("    </ho:CODING>\n");
        }
    }

    // SIGNAL
    for pdu in fibex.pdus() {
        for sig in pdu.signals() {
            let coding_id = coding_id_of(pdu.name(), sig.name());
            out.push_str(&format!(
                "    <ho:SIGNAL ID=\"{}\">\n",
                escape_xml(&id_of("SIGNAL", sig.name()))
            ));
            out.push_str(&format!(
                "      <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
                escape_xml(sig.name())
            ));
            if !sig.comment().is_empty() {
                out.push_str(&format!(
                    "      <ho:DESC>{}</ho:DESC>\n",
                    escape_xml(sig.comment())
                ));
            }
            out.push_str(&format!(
                "      <ho:CODING-REF REF-TYPE=\"ho:CODING-TYPE\" ID-REF=\"{}\"/>\n",
                escape_xml(&coding_id)
            ));
            out.push_str("    </ho:SIGNAL>\n");
        }
    }

    // PDU
    for pdu in fibex.pdus() {
        out.push_str(&format!(
            "    <fx:PDU ID=\"{}\">\n",
            escape_xml(&id_of("PDU", pdu.name()))
        ));
        out.push_str(&format!(
            "      <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
            escape_xml(pdu.name())
        ));
        if !pdu.comment().is_empty() {
            out.push_str(&format!(
                "      <ho:DESC>{}</ho:DESC>\n",
                escape_xml(pdu.comment())
            ));
        }
        out.push_str(&format!(
            "      <fx:PDU-TYPE>{}</fx:PDU-TYPE>\n",
            match pdu.kind() {
                PduKind::Static => "STATIC-PDU",
                PduKind::Dynamic => "DYNAMIC-PDU",
                PduKind::Event => "EVENT-PDU",
            }
        ));
        out.push_str(&format!(
            "      <fx:PDU-LENGTH>{}</fx:PDU-LENGTH>\n",
            pdu.length()
        ));
        if !pdu.signals().is_empty() {
            out.push_str("      <fx:SIGNAL-INSTANCES>\n");
            for sig in pdu.signals() {
                out.push_str(&format!(
                    "        <fx:SIGNAL-INSTANCE ID=\"{}\">\n",
                    escape_xml(&id_of("SIGINST", &format!("{}.{}", pdu.name(), sig.name())))
                ));
                out.push_str(&format!(
                    "          <fx:SIGNAL-REF REF-TYPE=\"ho:SIGNAL-TYPE\" ID-REF=\"{}\"/>\n",
                    escape_xml(&id_of("SIGNAL", sig.name()))
                ));
                out.push_str(&format!(
                    "          <fx:START-BIT-POSITION>{}</fx:START-BIT-POSITION>\n",
                    sig.start_bit()
                ));
                out.push_str(&format!(
                    "          <fx:IS-HIGH-LOW-BYTE-ORDER>{}</fx:IS-HIGH-LOW-BYTE-ORDER>\n",
                    match sig.byte_order() {
                        ByteOrder::BigEndian => "true",
                        ByteOrder::LittleEndian => "false",
                    }
                ));
                out.push_str("        </fx:SIGNAL-INSTANCE>\n");
            }
            out.push_str("      </fx:SIGNAL-INSTANCES>\n");
        }
        out.push_str("    </fx:PDU>\n");
    }

    // FRAME
    for frame in fibex.frames() {
        out.push_str(&format!(
            "    <fx:FRAME ID=\"{}\">\n",
            escape_xml(&id_of("FRAME", frame.name()))
        ));
        out.push_str(&format!(
            "      <ho:SHORT-NAME>{}</ho:SHORT-NAME>\n",
            escape_xml(frame.name())
        ));
        if !frame.comment().is_empty() {
            out.push_str(&format!(
                "      <ho:DESC>{}</ho:DESC>\n",
                escape_xml(frame.comment())
            ));
        }
        out.push_str(&format!(
            "      <fx:FRAME-LENGTH>{}</fx:FRAME-LENGTH>\n",
            frame.length()
        ));
        out.push_str(&format!(
            "      <fx:PAYLOAD-PREAMBLE>{}</fx:PAYLOAD-PREAMBLE>\n",
            if frame.payload_preamble() { "true" } else { "false" }
        ));
        if !frame.pdus().is_empty() {
            out.push_str("      <fx:PDU-MAPPINGS>\n");
            for m in frame.pdus() {
                out.push_str(&format!(
                    "        <fx:PDU-MAPPING ID=\"{}\">\n",
                    escape_xml(&id_of("PDUMAP", &format!("{}.{}", frame.name(), m.pdu_name)))
                ));
                out.push_str(&format!(
                    "          <fx:PDU-REF REF-TYPE=\"fx:PDU-TYPE\" ID-REF=\"{}\"/>\n",
                    escape_xml(&id_of("PDU", &m.pdu_name))
                ));
                out.push_str(&format!(
                    "          <fx:START-BIT-POSITION>{}</fx:START-BIT-POSITION>\n",
                    m.start_position
                ));
                out.push_str(
                    "          <fx:IS-HIGH-LOW-BYTE-ORDER>true</fx:IS-HIGH-LOW-BYTE-ORDER>\n",
                );
                out.push_str("        </fx:PDU-MAPPING>\n");
            }
            out.push_str("      </fx:PDU-MAPPINGS>\n");
        }
        out.push_str("    </fx:FRAME>\n");
    }

    out.push_str("  </fx:ELEMENTS>\n");
    out.push_str("</fx:FIBEX>\n");
    out
}

/// 生成稳定的内部 ID（不参与跨文件引用，仅保证本文件内一致）
fn id_of(prefix: &str, name: &str) -> String {
    format!("{}_{}", prefix, name)
}

fn coding_id_of(pdu: &str, sig: &str) -> String {
    format!("CODING_{}_{}", pdu, sig)
}

fn fmt_f64(v: f64) -> String {
    if (v - v.round()).abs() < f64::EPSILON {
        format!("{}", v as i64)
    } else {
        format!("{}", v)
    }
}
